#!/bin/bash

set -x 
set -e

# SETUP development environment
yum groupinstall -y 'Development Tools'
if ! rpm -q gtk2-devel &> /dev/null ; then
    # while we do not link to these libraries they are 
    # needed for 'autogen.sh' to work correctly.
    yum install -y gtk2-devel
fi

BUILDROOT=$PWD
TOPDIR=/home/iupui_npad

# build web100 userland library for NDT
if [ ! -f $TOPDIR/build/lib/libweb100.a ] ; then
    rm -rf web100-userland
    [ -d web100-userland ] || \
        git clone git@github.com:npad/web100-userland.git
    pushd web100-userland
	patch -p1 < ../mlab-support/lib/web100_userland-1.8-vsys.patch 
        ./autogen.sh
        ./configure --prefix=$TOPDIR/build  --disable-gtk2 --disable-gtktest
        make
        make install
        git show --quiet > $TOPDIR/version || :
    popd
fi

# build NPAD
if [ ! -f $TOPDIR/build/DiagServer.py ] ; then
    rm -rf npad
    rm -rf sidestream
    [ -d npad ] || \
	git clone git@github.com:stephen-soltesz/npad.git
    [ -d sidestream ] || \
	git clone git@github.com:stephen-soltesz/sidestream.git

    pushd npad
	export LD_LIBRARY_PATH=/home/iupui_npad/build/lib/
	export PYTHONPATH=/home/iupui_npad/build/lib/python2.6/site-packages/
	cp $BUILDROOT/mlab-support/lib/config.xml ./
	./config.py -a
	(cd pathdiag; make saveswig)
	make
	make install
	git show --quiet >> $TOPDIR/version || :
    popd
fi
 
# install init scripts
cp -r mlab-support/init $TOPDIR/

# treat mlab-support/lib as a configuration directory
cp -r mlab-support/lib $TOPDIR/conf
# this file will be generated by initialize.sh
rm -f $TOPDIR/VAR/www/index.html
# this is the template from which index.html is generated.
mv    $TOPDIR/VAR/www/diag_form.html $TOPDIR/conf/

# try to preserve backward compatibility with filenames/purpose
cp -f $TOPDIR/version $TOPDIR/VAR/www/tartime.txt

# log copying
cp -f mlab-support/bin/redisplay.py $TOPDIR/build/
cp -f mlab-support/src/favicon.ico $TOPDIR/VAR/www/

# sidestream
cp -f sidestream/doside $TOPDIR/build/bin
cp -f sidestream/exitstats.py $TOPDIR/build/bin
cp -f sidestream/tdump8000.py $TOPDIR/build/bin
cp -f sidestream/mkSample.py $TOPDIR/build/bin

# ensure environment variables point to the build/* directory
cat <<\EOF > $TOPDIR/.bash_profile
source /etc/mlab/slice-functions
export PATH=$PATH:$SLICEHOME/build/bin:$SLICEHOME/build
export LD_LIBRARY_PATH=$SLICEHOME/build/lib
export PYTHONPATH=$SLICEHOME/build/lib/python2.6/site-packages
EOF
# generate a global config file for easy import
cat <<\EOF > $TOPDIR/conf/config.sh
RSYNCDIR=/var/spool/iupui_npad
RSYNCDIR_SS=/var/spool/iupui_npad/SideStream
RSYNCDIR_NPAD=/var/spool/iupui_npad/NPAD.v1

# read local values into variables
MYNODE=`cat $SLICEHOME/VAR/MYNODE 2> /dev/null`
MYADDR=`cat $SLICEHOME/VAR/MYADDR 2> /dev/null`
MYFQDN=`cat $SLICEHOME/VAR/MYFQDN 2> /dev/null`
MYLOCATION=`cat $SLICEHOME/VAR/MYLOCATION 2> /dev/null`
EOF
tar -C $TOPDIR -cvf iupui_npad.tar .

